-- require("sidebar-nvim").setup({
--     disable_default_keybindings = 0,
--     bindings = nil,
--     open = true,
--     side = "left",
--     initial_width = 30,
--     hide_statusline = false,
--     update_interval = 1000,
--     sections = {"files", "git", "diagnostics", },
--     section_separator = {"", "-----", ""},
--     section_title_separator = {""},
--     containers = {
--         attach_shell = "/bin/sh", show_all = true, interval = 5000,
--     },
--     files = {
--         icon = "",
--         show_hidden = true,
--         ignored_paths = {"%.git$"}
--     },
--     datetime = { format = "%a %b %d, %H:%M", clocks = { { name = "local" } } },
--     todos = { ignored_paths = { "~" } },
-- })
